spring:
  application:
    name: spring-jdbc-demo

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin123
    driver-class-name: org.postgresql.Driver

